name: CI

env:
  CI: true

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Lint
        run: yarn lint
      - name: Notify discord
        uses: ./.github/actions/notify-discord
        with:
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Build
        run: yarn build
      - name: Notify discord
        uses: ./.github/actions/notify-discord
        with:
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test
      - name: Notify discord
        uses: ./.github/actions/notify-discord
        with:
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}

  integration-goerli:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Set up hardhat config
        run: .github/scripts/setup-hardhat-config.sh ${{secrets.GOERLI_RPC}} ${{secrets.MUMBAI_RPC}} ${{secrets.MAINNET_RPC}} ${{secrets.POLYGON_RPC}}
      - name: Build
        run: yarn build
      - name: Test Goerli
        run: yarn test:goerli
      - name: Notify discord
        uses: ./.github/actions/notify-discord
        with:
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}

  integration-mumbai:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Set up hardhat config
        run: .github/scripts/setup-hardhat-config.sh ${{secrets.GOERLI_RPC}} ${{secrets.MUMBAI_RPC}} ${{secrets.MAINNET_RPC}} ${{secrets.POLYGON_RPC}}
      - name: Build
        run: yarn build
      - name: Test Mumbai
        run: yarn test:mumbai
      - name: Notify discord
        uses: ./.github/actions/notify-discord
        with:
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}

  integration-mainnet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Set up hardhat config
        run: .github/scripts/setup-hardhat-config.sh ${{secrets.GOERLI_RPC}} ${{secrets.MUMBAI_RPC}} ${{secrets.MAINNET_RPC}} ${{secrets.POLYGON_RPC}}
      - name: Build
        run: yarn build
      - name: Test Mainnet
        run: yarn test:mainnet
      - name: Notify discord
        uses: ./.github/actions/notify-discord
        with:
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
